doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            # Identities
            card_dav_account_id: App\Component\CardDav\Infrastructure\Doctrine\Type\CardDavAccountIdType
            card_dav_address_book_id: App\Component\CardDav\Infrastructure\Doctrine\Type\CardDavAddressBookIdType
            contact_activity_id: App\Component\Contact\Infrastructure\Doctrine\Type\ContactActivityIdType
            contact_id: App\Component\Contact\Infrastructure\Doctrine\Type\ContactIdType
            company_id: App\Component\Contact\Infrastructure\Doctrine\Type\CompanyIdType
            user_id: App\Infrastructure\Doctrine\Type\Identity\UserIdType
            # ValueObject
            email: App\Infrastructure\Doctrine\Type\EmailType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Component\CardDav\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/CardDav/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Component\CardDav\Domain\Entity'
            App\Component\Contact\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/Contact/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Component\Contact\Domain\Entity'

#                alias: CardDav
            App\Infrastructure\Doctrine\EntityModel:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Infrastructure\Doctrine\EntityModel'
#                alias: YourDomain
            App\Infrastructure\Doctrine\Entity:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity'
                prefix: 'App\Infrastructure\Doctrine\Entity'
#                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
