doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            # Identities
            card_dav_account_id: App\Infrastructure\Doctrine\Type\Identity\CardDavAccountIdType
            card_dav_address_book_id: App\Infrastructure\Doctrine\Type\Identity\CardDavAddressBookIdType
            contact_activity_id: App\Infrastructure\Doctrine\Type\Identity\ContactActivityIdType
            contact_id: App\Infrastructure\Doctrine\Type\Identity\ContactIdType
            company_id: App\Infrastructure\Doctrine\Type\Identity\CompanyIdType
            user_id: App\Infrastructure\Doctrine\Type\Identity\UserIdType
            imap_account_id: \App\Infrastructure\Doctrine\Type\Identity\ImapAccountIdType
            imap_mail_id: \App\Infrastructure\Doctrine\Type\Identity\ImapMailIdType
            imap_mailbox_id: \App\Infrastructure\Doctrine\Type\Identity\ImapMailboxIdType
            # ValueObject
            email: App\Infrastructure\Doctrine\Type\EmailType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Component\CardDav\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/CardDav/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Component\CardDav\Domain\Entity'
            App\Component\Contact\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/Contact/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Component\Contact\Domain\Entity'
            App\Component\Security\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/Security/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Component\Security\Domain\Entity'
            App\Component\WebMail\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/WebMail/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Component\WebMail\Domain\Entity'
#            App\Component\WebMail\Domain\Entity\ImapMailAuthor:
#                is_bundle: false
#                type: xml
#                dir: '%kernel.project_dir%/src/Component/WebMail/Infrastructure/Doctrine/Mapping/ImapAuthor.orm.xml'
#                prefix: 'App\Component\WebMail\Domain\Entity\ImapMailAuthor'
#                exclude: true

##                alias: CardDav
#            App\Infrastructure\Doctrine\EntityModel:
#                is_bundle: false
#                type: xml
#                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping'
#                prefix: 'App\Infrastructure\Doctrine\EntityModel'
##                alias: YourDomain
#            App\Infrastructure\Doctrine\Entity:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity'
#                prefix: 'App\Infrastructure\Doctrine\Entity'
##                alias: App
#        resolve_target_entities:
#            \App\Component\WebMail\Domain\Entity\ImapMailAuthor: \App\Component\Contact\Domain\Entity\Contact

#        entity_managers:
        schema_ignore_classes:
            - App\Component\WebMail\Domain\Entity\ImapMailAuthor
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
