framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                 options:
#                     use_notify: true
#                     check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Component\DirectCommunicationHub\Application\Command\SyncImapAccount: async
            App\Component\DirectCommunicationHub\Application\Command\SyncImapMailbox: async
#            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
#            App\Presentation\Async\Message\SyncMailbox: async
#            App\Presentation\Async\Message\SyncMail: async
#            App\Presentation\Async\Message\SyncAddressBook: async

