twig:
    default_path: '%kernel.project_dir%/src/Presentation/templates'
    paths:
        'src/Presentation/templates/layout': 'layout'
        'src/Presentation/templates/pages/contact': 'contact'
    form_themes:
        - '@Tabler/layout/form-theme.html.twig'

when@test:
    twig:
        strict_variables: true
