twig_component:
    anonymous_template_directory: '@common/components/'
    defaults:
        # Namespace & directory for components
        App\Presentation\Common\Twig\Component\: '@common/components/'
        App\Presentation\WebMail\Twig\Component\: '@webmail/components/'
