version: '3.2'

volumes:
  mysql_db:
  postgres_db:

services:
  traefik:
    image: traefik:v2.10
    hostname: traefik.localhost
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.docker/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik_https.service: api@internal

  web:
    image: registry.corrin.j3ck3l.me:443/jeckel-lab/php-apache-dev:8.3
    volumes:
      - ./:/var/www
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/crm_bridge?serverVersion=16&charset=utf8"
      SUPERVISOR_URL: "http://worker:9001/RPC2"
      SUPERVISOR_USER: "user"
      SUPERVISOR_PASSWORD: "password"
    env_file:
      - .env.local
    depends_on:
      - postgres
      - traefik

  worker:
    image: registry.corrin.j3ck3l.me:443/jeckel-lab/php-supervisor-dev:8.3
    hostname: worker.localhost
    volumes:
      - ./:/var/www
      - ./.docker/worker/conf.d/:/etc/supervisor/conf.d/:ro
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/crm_bridge?serverVersion=16&charset=utf8"
    depends_on:
      - postgres
      - traefik

  postgres:
    image: postgres:16
    hostname: postgres.localhost
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "crm_bridge"
    ports:
      - "5432:5432"

  ngrok:
    image: ngrok/ngrok:alpine
    hostname: ngrok.localhost
    labels:
      traefik.enable: true
      traefik.http.services.ngrok.loadbalancer.server.port: 4040
    env_file:
      - .env.local
    entrypoint: ""
    command: sh -c "ngrok tunnel --label edge=$$NGROK_EDGE http://web:80"
    depends_on:
      - traefik
