version: '3.2'

volumes:
  mysql_db:

services:
  traefik:
    image: traefik:v2.10
    hostname: traefik.localhost
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.docker/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik_https.service: api@internal

  web:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ./:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
    depends_on:
      - php-fpm
      - traefik

  php-fpm:
    image: crm-bridge/php-fpm:latest
    hostname: php-fpm.localhost
    working_dir: /application
    volumes:
      - ./:/application
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/crm-bridge?serverVersion=8&charset=utf8mb4"
      MESSENGER_TRANSPORT_DSN: "amqp://user:password@rabbitmq:5672/crm_bridge/messages"
      SUPERVISOR_URL: "http://worker:9001/RPC2"
      SUPERVISOR_USER: "user"
      SUPERVISOR_PASSWORD: "password"
      CALENDLY_WEBHOOK_URI: "https://9da4-88-170-19-46.ngrok-free.app/webhook/calendly"
    env_file:
      - .env.dev.local
    depends_on:
      - mysql
      - rabbitmq

  worker:
    image: crm-bridge/worker:latest
    hostname: worker.localhost
    working_dir: /application
    volumes:
      - ./:/application
      - ./.docker/worker/conf.d/:/etc/supervisor/conf.d/:ro
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/crm-bridge?serverVersion=8&charset=utf8mb4"
      MESSENGER_TRANSPORT_DSN: "amqp://user:password@rabbitmq:5672/crm_bridge/messages"
    depends_on:
      - mysql
      - rabbitmq
      - traefik

  mysql:
    image: mysql:8.0
    hostname: mysql.localhost
    volumes:
      - mysql_db:/var/lib/mysql
      - ./.docker/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "crm-bridge"
    ports:
      - "${MYSQL_PUBLIC_PORT:-3306}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq.localhost
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
      RABBITMQ_DEFAULT_VHOST: 'crm_bridge'
    labels:
      traefik.enable: true
      traefik.http.services.rabbitmq.loadbalancer.server.port: 15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - traefik

  ngrok:
    image: ngrok/ngrok:alpine
    hostname: ngrok.localhost
    labels:
      traefik.enable: true
      traefik.http.services.ngrok.loadbalancer.server.port: 4040
    env_file:
      - .env.dev.local
    command: http web:80

