version: '3.2'

volumes:
  mysql_db:

services:
  traefik:
    image: traefik:v2.10
    hostname: traefik.localhost
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.docker/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik_https.service: api@internal

  web:
    image: registry.corrin.j3ck3l.me:443/jeckel-lab/php-apache-dev:8.3
    volumes:
      - ./:/var/www
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/crm-bridge?serverVersion=8&charset=utf8mb4"
      SUPERVISOR_URL: "http://worker:9001/RPC2"
      SUPERVISOR_USER: "user"
      SUPERVISOR_PASSWORD: "password"
    env_file:
      - .env.local
    depends_on:
      - mysql
      - traefik

  worker:
    image: registry.corrin.j3ck3l.me:443/jeckel-lab/php-supervisor-dev:8.3
    hostname: worker.localhost
    volumes:
      - ./:/var/www
      - ./.docker/worker/conf.d/:/etc/supervisor/conf.d/:ro
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/crm-bridge?serverVersion=8&charset=utf8mb4"
    depends_on:
      - mysql
      - traefik

  mysql:
    image: mysql:8.0
    hostname: mysql.localhost
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "crm-bridge"
    ports:
      - "${MYSQL_PUBLIC_PORT:-3306}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  ngrok:
    image: ngrok/ngrok:alpine
    hostname: ngrok.localhost
    labels:
      traefik.enable: true
      traefik.http.services.ngrok.loadbalancer.server.port: 4040
    env_file:
      - .env.local
    entrypoint: ""
    command: sh -c "ngrok tunnel --label edge=$$NGROK_EDGE http://web:80"
    depends_on:
      - traefik
