<?php

/**
 * @author: Julien Mercier-Rojas <julien@jeckel-lab.fr>
 * Created at: 05/02/2024
 */

declare(strict_types=1);

namespace App\Presentation\Setup\Form;

use App\Component\WebMail\Application\Command\CreateImapAccount;
use Override;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImapAccountFormType extends AbstractType
{
    /**
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    #[Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                child: 'name',
                type: TextType::class,
                options: [
                    'label' => 'setup.imap.field.label'
                ]
            )
            ->add(
                child: 'uri',
                type: TextType::class,
                options: [
                    'label' => 'setup.imap.field.host'
                ]
            )
            ->add(
                child: 'login',
                type: TextType::class,
                options: [
                    'label' => 'setup.imap.field.login'
                ]
            )
            ->add(
                child: 'password',
                type: PasswordType::class,
                options: [
                    'label' => 'setup.imap.field.password'
                ]
            )
            ->add(
                child:'save',
                type: SubmitType::class,
                options: ['label' => 'action.save']
            );
    }

    /**
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    #[Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'hx-post' => null,
            'data_class' => CreateImapAccount::class,
            'empty_data' => function (FormInterface $form) {
                return new CreateImapAccount(
                    name: $form->get('name')->getData(), /** @phpstan-ignore-line */
                    uri: $form->get('uri')->getData(), /** @phpstan-ignore-line */
                    login: $form->get('login')->getData(), /** @phpstan-ignore-line */
                    password: $form->get('password')->getData() /** @phpstan-ignore-line */
                );
            },
        ]);
    }

    #[Override]
    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        if ($options['hx-post'] !== null) {
            $view->vars['attr']['hx-post'] = $options['hx-post'];
        }
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}
