<?php

namespace App\Presentation\Setup\Form;

use App\Component\CardDav\Application\Command\UpdateAddressBooksActivation;
use App\Component\Shared\Identity\CardDavAccountId;
use Override;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SyncedAddressBookFormType extends AbstractType
{
    #[Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                child:'accountId',
                type: HiddenType::class,
                options: ['data' => $options['accountId']]
            )
            ->add(
                child: 'syncedAddressBooks',
                type: ChoiceType::class,
                options: [
                    'choices' => $options['addressBooks'],
                    'label' => 'setup.card_dav.field.sync_address_books',
                    'multiple' => true,
                    'expanded' => true
                ]
            )
            ->add(
                child:'save',
                type: SubmitType::class,
                options: ['label' => 'action.select']
            )
        ;
    }

    #[Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'accountId' => null,
            'addressBooks' => [],
            'hx-post' => null,
        ]);
    }

    #[Override]
    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        if ($options['hx-post'] !== null) {
            $view->vars['attr']['hx-post'] = $options['hx-post'];
        }
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}
