<?php

/**
 * @author: Julien Mercier-Rojas <julien@jeckel-lab.fr>
 * Created at: 15/01/2024
 */

declare(strict_types=1);

namespace App\Presentation\Async\Handler;

use App\Presentation\Async\WebHook\WebHook;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]
class CalDotComHandler extends WebHookHandler
{
    public function __invoke(WebHook $webhook): void
    {
        parent::__invoke($webhook); // TODO: Change the autogenerated stub
    }
}
